version: '3.8'
services:
  php:
    image: php:8.2-apache
    container_name: ntryjob_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && 
               apache2-foreground"
  
  db:
    image: mysql:8.0
    container_name: ntryjob_db
    environment:
      MYSQL_ROOT_PASSWORD: 7394
      MYSQL_DATABASE: ntryjob
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
